### ISSUE TITLE
 Concept "java:InvokesOverriddenMethod" should be replaced by "java:VirtualInvokes"

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqa-java-plugin#13]
The name of the concept is not clear enough, therefore it should be deprecated and replaced by "java:InvokesVirtually"

**Comment by obfischer** [comment]
Is this a change done for 1.8.0?

**Comment by DirkMahler** [comment]
Yes, already implemented.

**Comment by obfischer** [comment]
Just ask to see if I assigned the correct milestone.
