### ISSUE TITLE
Upgrade the ASM version used by the Java plugin to be able to scan Java 18 bytecode

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-java-plugin#33]
### Feature Description
I, as product owner of jQA,
would like to see jQA to be able to scan also Java 18 bytecode,
to that we can scan also projects using the latest Java release.

### Additional information on the requested Feature
none

### How to Test
To test this feature scan a project using a JDK for Java 18.

### Available Test data
none

### Definition of Done for the Implementers
- [x] Added a note on the new feature to the release notes

**Comment by DirkMahler** [comment]
Verified with Java 21.
