### ISSUE TITLE
Java Scanner does not recognize Method references as :INVOKES

### ISSUE THREAD

**Issue by gernotbragenheim** [jQAssistant/jqa-java-plugin#35]
### Bug Description
While the scanner recognizes method and constructor calls as :INVOKES-relations, such as:
_maybeMyTestClassB.ifPresent(myTestClassB -> myTestClassB.doSomeAction());_

it does not recognize method references such as:
_maybeMyTestClassB.ifPresent(MyTestClassB::doSomeAction);_

### Expected Behaviour
jQAssistant should treat method references as the same kind of :INVOKES-relation as usual method calls because effectively they do the same and the method is invoked.

### Your Environment
- *JDK:* jdk1.8.0_281, jdk-11.0.13
- *OS:* Windows 10.0.19042
- *jQA:* 1.11.1

### How can we reproduce the bug?
Demo in my github: https://github.com/gernotbragenheim/jqassistantMethodReferenceTest

### How could we have prevented this Bug?
_Remove this hint: Is there anything we could have done to prevent this problem?_

### Definition of Done for the Implementers
_Remove this hint: these checkboxes can be checked like this: [x]_
- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by DirkMahler** [comment]
Method references and lambdas rely on invokeDynamic which has not been supported yet. Implementation and tests have been added.
