### ISSUE TITLE
Correct byteCodeVersion for Java 1.1

### ISSUE THREAD

**Issue by hmozaffari** [jQAssistant/jqa-java-plugin#38]
Seems “byteCodeVersion” returned for Java 1.1 in some cases is 196653. So in addition to 45, rule needs to map 196653 to Java 1.1. For example try “aspectjtools-1.9.2.jar” Jar file. Version of classes there is 45.3 but Java plugin set its byteCodeVersion to 196653:

https://github.com/jQAssistant/jqa-java-plugin/blob/a94e2a104696af1d5f6d55fe9edf302bf04c38fa/src/main/resources/META-INF/jqassistant-rules/java.xml#L285

**Comment by DirkMahler** [comment]
According to https://bugs.openjdk.org/browse/JDK-8273403 it seems that the value indicates a class format error. The concept has been changed such that it now sets a value "Unknown" if no mapping is known.
