### ISSUE TITLE
DEPENDS_ON should contains information

### ISSUE THREAD

**Issue by opensource21** [jQAssistant/jqa-java-plugin#7]
It would be great if jqa-java-plugin/src/main/resources/META-INF/jqassistant-rules/dependency.xml contains information about the weight and the dependencies as a list. With this information a check of package cycles could be more precise. See a [similar example](https://github.com/opensource21/sze/blob/46f8ca0d26832a602d341042988f8c8bfd92cf6f/jqassistant/layer.adoc) in ascii-doc

**Comment by jdufner** [comment]
Please explain how the weight of DEPENDS_ON is calculated.

**Comment by DirkMahler** [comment]
The value of weight is the counts of all usages to the type referenced by DEPENDS_ON, e.g. field, parameter or variable declarations of that type, occurences as annotations or annotation parameters, usage in inheritance, etc. 

In other words: You can treat it as the number of code occurrences to replace if you want to remove the dependency between the two types.

**Comment by DirkMahler** [comment]
@opensource21 Is this still relevant: if yes it would be good if you could provide a concrete example.

**Comment by opensource21** [comment]
I can't use jqassistant at the moment, so feel free to close it.
